# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rachel Lacy, Psy.D., P.C.
email: drrlacy@mdofficemail.com
street: 1805 Herrington Rd, Ste. 3-B
city: Lawrenceville GA 30043
phonenumber: 770-722-7827
fax: 770-760-0624
description: > # this means to ignore newlines until "baseurl:"
  Guidance for Purposeful Living
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.renewedbrain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
